name = "AmmerBatch"
authors = ["Vitor Cantarella, Johann Holdt"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Tidier = "f0413319-3358-4bb0-8e7c-0c83523a93bd"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
DrWatson = "2.18.0"
julia = "1.11.2"